import requests

class RequestManager:
    """
    Class for creating RequestManager.

    This class manages all related to HTTP requests.
    """
    def post(self, config, prompt):
        """
        Makes post request.

        Args:
            config (dict): The LLM configuration.
            prompt (str): The prompt to send to the LLM.
        """
        url = config["url"]
        headers = self._prepare_headers(config["api_key"])
        model = config["model_name"]
        payload = self._prepare_payload(model, prompt)

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()

            return self._get_response_content(response.json())
        except requests.exceptions.RequestException as e:
            raise Exception(f"An error occurred during the request to the '{model}' LLM: {e}")

    def check_connection(self, config):
        """
        Checks connection to the LLM.

        Args:
            config (dict): The LLM configuration.

        Raises:
            Exception: If connection to the LLM failed.
            Exception: If an error occurred during the request to the LLM.
        """
        url = config["url"]
        headers = self._prepare_headers(config["api_key"])
        model = config["model_name"]
        payload = self._prepare_payload(model, "What is the capital of France? Answer in English.")

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()

            content = self._get_response_content(response.json())

            if ('paris' not in content.lower()):
                raise Exception(f"Connection to the '{model}' LLM failed.")
            print(f"Successful connection to the '{model}' LLM.")
        except requests.exceptions.RequestException as e:
            raise Exception(f"An error occurred during the request to the '{model}' LLM: {e}")

    def _prepare_headers(self, api_key):
        """
        Prepares headers before sending it to the LLM.

        Args:
            api_key (str): The API key that should be added to the headers.

        Returns:
            dict: Prepared headers.
        """
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        return headers

    def _prepare_payload(self, model, prompt):
        """
        Prepares the payload before sending it to the LLM.

        Args:
            model (str): The model name that should be added to the payload.
            prompt (str): The prompt that should be added to the payload.

        Returns:
            dict: A payload with added data.
        """
        payload = {
            "model": model,
            "messages": [
                { "role": "system", "content": "You are a helpful assistant." },
                { "role": "user", "content": prompt }
            ]
        }

        return payload

    def _get_response_content(self, response):
        """
        Returns content generated by LLM.

        Args:
            response (dict): The response data.

        Returns:
            str: A content generated by LLM.
        """

        return response["choices"][0]["message"]["content"]
