import json
import requests

class RequestManager:
    """
    Class for creating RequestManager.

    This class manages all related to HTTP requests.
    """
    def post(self, config, prompt):
        """
        Makes post request.

        Args:
            config (dict): The LLM configuration.
            prompt (str): The prompt to send to the LLM.
        """
        print("Post")

    def check_connection(self, config):
        """
        Checks connection to the LLM.

        Args:
            config (dict): The LLM configuration.

        Raises:
            Exception: If connection to the LLM failed.
            Exception: If an error occurred during the request to the LLM.
        """
        url = config["url"]
        headers = config["headers"]
        payload = self._prepare_payload(config["payload"], "What is the capital of France? Answer in English.")
        scheme = config["response_content"]
        model = config["payload"]["model"]

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()

            content = self._get_response_content(response.json(), scheme)

            if ('paris' not in content.lower()):
                raise Exception(f"Connection to the '{model}' LLM failed.")
            print(f"Successful connection to the '{model}' LLM.")
        except requests.exceptions.RequestException as e:
            raise Exception(f"An error occurred during the request to the '{model}' LLM: {e}")

    def _prepare_payload(self, payload, prompt):
        """
        Prepares the payload before sending it to the LLM.

        Args:
            payload (dict): The payload that needs to be expanded with prompt.
            prompt (str): The prompt that should be inserted into the payload.

        Returns:
            dict: A payload with a prompt inserted.
        """
        return json.loads(json.dumps(payload).replace("{{prompt}}", prompt))

    def _get_response_content(self, data, scheme):
        """
        Returns content generated by LLM.

        Args:
            data (dict): The response data.
            scheme (list): The content search template.

        Returns:
            str: A content generated by LLM.
        """
        for item in scheme:
            data = data[item]

        return data
