[project]
name = "llmsploit"
version = "0.1.0"
description = "LLMsploit a vulnerability scanner for Large Language Models"
authors = [
    { name = "Oleksii Neretin", email = "oleksii.neretin@gmail.com" },
]
readme = "README.md"
keywords = [
    "llm",
    "llm-safety",
    "llm-security",
    "llm-risk-assessment",
    "llm-vulnerability-scanner"
]
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.5",
]
