[project]
name = "llmsploit"
version = "0.2.1"
description = "LLMsploit a vulnerability scanner for Large Language Models"
authors = [
    { name = "Oleksii Neretin", email = "oleksii.neretin@gmail.com" },
]
readme = "README.md"
keywords = [
    "llm",
    "llm-safety",
    "llm-security",
    "llm-risk-assessment",
    "llm-vulnerability-scanner"
]
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.1",
]
